import { v4 as uuid } from "uuid";

const link = "http://res.cloudinary.com/therajatg/image/upload/books";

export const products = [
  {
    _id: uuid(),
    img: `${link}/biographies/1_tlljcj.jpg`,
    title: "Karmayogi: A Biography of E. Sreedharan",
    author: "M S Ashokan",
    rating: 4.5,
    fastDelivery: false,
    oldPrice: 990,
    price: 699,
    categoryName: "Biographies",
    size: "S",
  },

  {
    _id: uuid(),
    img: `${link}/literature and fiction/1_maqnxo.jpg`,
    title: "The Book of Longings: A Novel",
    author: "Sue Monk Kidd",
    rating: 5.0,
    fastDelivery: false,
    oldPrice: 1435,
    price: 810,
    categoryName: "Literature & Fiction",
    size: "M",
  },
  {
    _id: uuid(),
    img: `${link}/business and money/2_s5gul6.jpg`,
    title: "Rich Dad Poor Dad",
    author: "Robert T. Kiyosaki",
    rating: 3.5,
    fastDelivery: true,
    oldPrice: 760,
    price: 430,
    categoryName: "Business & Money",
    size: "M",
  },

  {
    _id: uuid(),
    img: "http://res.cloudinary.com/therajatg/image/upload/books/parenting and relationships/4_yestpw.jpg",
    title: "The Opposite of Worry",
    author: "Lawrence J. Cohen",
    rating: 4.5,
    fastDelivery: true,
    oldPrice: 1640,
    price: 1120,
    categoryName: "Parenting & Relationships",
    size: "L",
  },

  {
    _id: uuid(),
    img: "http://res.cloudinary.com/therajatg/image/upload/books/business and money/1_vv9gr5.jpg",
    title: "Zero to One: Notes on Start Ups and the Future",
    author: "Peter Thiel",
    rating: 4.5,
    fastDelivery: false,
    oldPrice: 1060,
    price: 510,
    categoryName: "Business & Money",
    size: "XL",
  },
  {
    _id: uuid(),
    img: "http://res.cloudinary.com/therajatg/image/upload/books/new releases/5_yuzidb.jpg",
    title: "Youth and Truth: Unplug with Sadhguru",
    author: "Sadhguru",
    rating: 5.0,
    fastDelivery: false,
    oldPrice: 968,
    price: 469,
    categoryName: "New Releases",
    size: "S",
  },
  {
    _id: uuid(),
    img: "http://res.cloudinary.com/therajatg/image/upload/books/business and money/4_fkh9sy.jpg",
    title: "Thinking, Fast and Slow",
    author: "Daniel Kahneman",
    rating: 2.5,
    fastDelivery: true,
    oldPrice: 1130,
    price: 899,
    categoryName: "Business & Money",
    size: "XL",
  },

  {
    _id: uuid(),
    img: "http://res.cloudinary.com/therajatg/image/upload/books/parenting and relationships/3_jxevxs.jpg",
    title: "Family Wisdom",
    author: "Robin Sharma",
    rating: 4.0,
    fastDelivery: true,
    oldPrice: 872,
    price: 389,
    categoryName: "Parenting & Relationships",
    size: "M",
  },
  {
    _id: uuid(),
    img: "http://res.cloudinary.com/therajatg/image/upload/books/biographies/6_iccecn.jpg",
    title: "Milton Friedman: A Biography",
    author: "Lanny Ebenstein",
    rating: 5.0,
    fastDelivery: false,
    oldPrice: 1120,
    price: 860,
    categoryName: "Biographies",
    size: "M",
  },
  {
    _id: uuid(),
    img: "http://res.cloudinary.com/therajatg/image/upload/books/business and money/5_sdwhyq.jpg",
    title: "The Intelligent Investor",
    author: "Benjamin Graham",
    rating: 4.5,
    fastDelivery: true,
    oldPrice: 776,
    price: 450,
    categoryName: "Business & Money",
    size: "L",
  },
  {
    _id: uuid(),
    img: "http://res.cloudinary.com/therajatg/image/upload/books/literature and fiction/9_lgdze5.jpg",
    title: "The Cellist: A Novel",
    author: "Daniel Silva",
    rating: 2.0,
    fastDelivery: true,
    oldPrice: 1190,
    price: 1000,
    categoryName: "Literature & Fiction",
    size: "L",
  },

  {
    _id: uuid(),
    img: "http://res.cloudinary.com/therajatg/image/upload/books/new releases/4_tklydl.jpg",
    title: "Bruised Passports: Digital Nomads",
    author: "Savi Munjal ",
    rating: 5.0,
    fastDelivery: false,
    oldPrice: 1645,
    price: 799,
    categoryName: "New Releases",
    size: "XL",
  },

  {
    _id: uuid(),
    img: "http://res.cloudinary.com/therajatg/image/upload/books/parenting and relationships/2_ndqmlk.jpg",
    title: "Parenting Outside the Lines: Forget the Rules",
    author: "Meghan Leahy",
    rating: 3.5,
    fastDelivery: false,
    oldPrice: 895,
    price: 499,
    categoryName: "Parenting & Relationships",
    size: "S",
  },
  {
    _id: uuid(),
    img: "http://res.cloudinary.com/therajatg/image/upload/books/business and money/3_xoizff.jpg",
    title: "Think and Grow Rich",
    author: " Napoleon Hill",
    rating: 4.5,
    fastDelivery: true,
    oldPrice: 1065,
    price: 659,
    categoryName: "Business & Money",
    size: "XL",
  },

  {
    _id: uuid(),
    img: "http://res.cloudinary.com/therajatg/image/upload/books/biographies/5_i4wujz.jpg",
    title: "An Extraordinary Life",
    author: "Sadguru Patil",
    rating: 5.0,
    fastDelivery: true,
    oldPrice: 1460,
    price: 999,
    categoryName: "Biographies",
    size: "S",
  },
];
